#!/bin/bash
# Copy this file to /etc/init.d/ and chmod a+x
# To make SMTP server run on system start execute: sudo update-rc.d pysmtpd defaults 99 1
# To disable automatic execution: sudo update-rc.d -f pysmtpd remove
#
# Mailinator Python SMTPD startup script
# USAGE: sudo /etc/init.s/pysmtpd start|stop|restart
#
django_folder=/var/www/mailinator/
pid=/var/run/pysmtpd.pid

case "$1" in
start)
	if [ -e $pid ]
	then
		echo "Mailinator SMTPD already running"
	else
		echo "Starting Mailinator SMTPD"
		setsid /usr/bin/python $django_folder'manage.py' 'smtp_server' &
		echo $! >> $pid
	fi
	;;
stop)
	if [ -e $pid ]
	then
		echo "Stopping Mailinator SMTPD"
		kill $(cat $pid)
		rm $pid
	else
		echo "Mailinator SMTPD not running"
	fi
	;;
restart)
	echo "Restarting Mailinator SMTPD"
	if [ -e $pid ]
	then
		kill $(cat $pid)
	fi
	setsid /usr/bin/python $django_folder'manage.py' 'smtp_server' &
	echo $! > $pid
	;;
*)
echo "Mailinator Python SMTPD startup script"
echo "Usage: {start|stop|restart}"
exit 1
esac
exit 0
